apiVersion: skaffold/v4beta1
kind: Config
deploy:
  helm:
    releases:
      - name: dapr
        repo: https://dapr.github.io/helm-charts/
        remoteChart: dapr
        version: "1.9.5"
        setValues:
          "dapr_config_chart_included": false
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest" # NOTE: fix tag
  artifacts:
    - image: hello
      context: .
    - image: daprwithmiddleware
      context: .
      docker:
        dockerfile: Dockerfile.dapr
manifests:
  rawYaml:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/configuration.yaml
  - manifests/wasm.yaml
