apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - name: dapr
    port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    app: hello
  type: ClusterIP
status:
  loadBalancer: {}
